import type { GeneratedRow } from "./types";

function escapeCsv(value: unknown): string {
  const s = value == null ? "" : Array.isArray(value) ? value.join("|") : String(value);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function toJson(rows: GeneratedRow[]): string {
  return JSON.stringify(rows, null, 2);
}

export function toCsv(rows: GeneratedRow[]): string {
  if (rows.length === 0) return "";
  const keys = Array.from(
    rows.reduce((set, row) => {
      Object.keys(row).forEach((k) => set.add(k));
      return set;
    }, new Set<string>()),
  );
  const header = keys.join(",");
  const body = rows
    .map((row) => keys.map((k) => escapeCsv(row[k])).join(","))
    .join("\n");
  return `${header}\n${body}`;
}

export function toPlaywrightFixture(rows: GeneratedRow[]): string {
  return `// Generated by QA Forge — negative/attack payloads are for negative tests only.
import { test as base } from '@playwright/test';

export type QaForgeFixtures = {
  qaCases: typeof qaCases;
};

export const qaCases = ${JSON.stringify(rows, null, 2)} as const;

export const test = base.extend<QaForgeFixtures>({
  qaCases: async ({}, use) => {
    await use(qaCases);
  },
});
`;
}

export function toTestEachSnippet(rows: GeneratedRow[]): string {
  const compact = rows.map((r) => ({
    id: r.id,
    case: r.case,
    expectHint: r.expectHint,
    ...Object.fromEntries(
      Object.entries(r).filter(
        ([k]) => !["id", "case", "tags", "expectHint"].includes(k),
      ),
    ),
  }));

  return `// Generated by QA Forge — label attack payloads as negative-test only.
import { test, expect } from '@playwright/test';

const cases = ${JSON.stringify(compact, null, 2)};

test.describe('QA Forge generated cases', () => {
  for (const row of cases) {
    test(\`\${row.id} [\${row.case}] expect=\${row.expectHint}\`, async ({ page }) => {
      // TODO: wire selectors for your app under test
      // Example:
      // await page.goto('/login');
      // if ('email' in row) await page.getByLabel('Email').fill(String(row.email));
      // if ('password' in row) await page.getByLabel('Password').fill(String(row.password));
      // await page.getByRole('button', { name: /submit|login|sign/i }).click();
      // if (row.expectHint === 'should_pass') {
      //   await expect(page).toHaveURL(/dashboard|home|success/i);
      // } else {
      //   await expect(page.getByRole('alert')).toBeVisible();
      // }
      expect(row.id).toBeTruthy();
    });
  }
});
`;
}
